### ISSUE TITLE
SQL File Missing

### ISSUE THREAD

**Issue by gamergabbar** [shanuraj715/GaanaWorld.In#1]
Hello Sir, SQL File Is Missing In This Script.

**Comment by gamergabbar** [comment]
?????

**Comment by shanuraj715** [comment]
This is not a free project. You have to pay for this. You can view the demo on https://gaanaworld.in and https://djsumitstm.in
If you want to purchase you can contact me on my WhatsApp: +91-9877936035
Thank You...
